---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# late.rest

<!-- badges: start -->
<!-- badges: end -->

The goal of late.rest is to implement the approach to estimating LATE based on a Test-and-Select method as described in [Hazard and Lowe (2023)](https://www.dropbox.com/s/x7kzrggcy9a614x/LATEPS_Working_Paper.pdf?dl=0)

## Installation

You can install the development version of late.rest from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("simon-lowe/late.rest")
```

## Example

The example below shows basic use with simulated data:

```{r example}
# Loading packages
library(fixest)
library(late.rest)

# Generate a simulated dataset
data <- sim.data()

# Create a predicted compliance score
data2 <- create.score.groups(data, treat = "d", instrument = "z", controls = ~x,
                             n_groups = 10)

# Print summary of predicted compliance scores
summary(data2$pred_p)

# Run a standard IV
reg1 <- feols(data = data2, y ~ 1 | d ~ z)

# Run basic test-and-select method
reg2 <- run.late.rest(data = data2, yname = "y", treat = "d", instrument = "z", controls = ~g)

# Run basic test-and-select method
reg3 <- run.late.rest(data = data2, yname = "y", treat = "d", instrument = "z",
                                   controls = ~score_g)

# Comparing both regressions
etable(reg1, reg2, reg3)
```


<!-- You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this. You could also use GitHub Actions to re-render `README.Rmd` every time you push. An example workflow can be found here: <https://github.com/r-lib/actions/tree/v1/examples>. -->

<!-- You can also embed plots, for example: -->

<!-- ```{r pressure, echo = FALSE} -->
<!-- plot(pressure) -->
<!-- ``` -->

<!-- In that case, don't forget to commit and push the resulting figure files, so they display on GitHub and CRAN. -->
